// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjKzFM7Ho55uLoDihuxNyYr1RRnj2kz9g',
    appId: '1:466200760101:web:ad3a0ca1ac889eab0b14cc',
    messagingSenderId: '466200760101',
    projectId: 'countdownoneweek',
    authDomain: 'countdownoneweek.firebaseapp.com',
    storageBucket: 'countdownoneweek.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVX8cR2RC1Sjld3TtzxsUh6T5sHZCCTfg',
    appId: '1:466200760101:android:b3e2ee34efc135950b14cc',
    messagingSenderId: '466200760101',
    projectId: 'countdownoneweek',
    storageBucket: 'countdownoneweek.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6NFsLZMLykJ-NeBcYQUmxc1cZSJkyVqU',
    appId: '1:466200760101:ios:e8b8e027659a5bb50b14cc',
    messagingSenderId: '466200760101',
    projectId: 'countdownoneweek',
    storageBucket: 'countdownoneweek.appspot.com',
    iosBundleId: 'com.example.within3week',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6NFsLZMLykJ-NeBcYQUmxc1cZSJkyVqU',
    appId: '1:466200760101:ios:e8b8e027659a5bb50b14cc',
    messagingSenderId: '466200760101',
    projectId: 'countdownoneweek',
    storageBucket: 'countdownoneweek.appspot.com',
    iosBundleId: 'com.example.within3week',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjKzFM7Ho55uLoDihuxNyYr1RRnj2kz9g',
    appId: '1:466200760101:web:fd0325aa29db8dc50b14cc',
    messagingSenderId: '466200760101',
    projectId: 'countdownoneweek',
    authDomain: 'countdownoneweek.firebaseapp.com',
    storageBucket: 'countdownoneweek.appspot.com',
  );
}
